namespace VectorFlow.Finance.Domain.Workspaces;

/// <summary>
/// Strongly typed identifier for a Finance-owned workspace aggregate.
/// Generated by the system; never entered manually in UI.
/// </summary>
public readonly record struct FinanceWorkspaceId
{
    public Guid Value { get; }

    public FinanceWorkspaceId(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException("Finance workspace id must not be empty.", nameof(value));
        }

        Value = value;
    }

    public static FinanceWorkspaceId New() => new(Guid.NewGuid());

    public override string ToString() => Value.ToString();
}
