// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectorFlow.Finance.Infrastructure.Persistence;

#nullable disable

namespace VectorFlow.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260719185841_AddInvoices")]
    partial class AddInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("VectorFlow.Finance.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanceWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinanceWorkspaceId")
                        .HasDatabaseName("IX_Accounts_FinanceWorkspaceId");

                    b.HasIndex("FinanceWorkspaceId", "CodeNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_FinanceWorkspaceId_CodeNormalized");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanceWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinanceWorkspaceId")
                        .HasDatabaseName("IX_Invoices_FinanceWorkspaceId");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Invoices.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_InvoiceLines_InvoiceId");

                    b.HasIndex("InvoiceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_InvoiceLines_InvoiceId_Sequence");

                    b.ToTable("InvoiceLines", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.JournalEntries.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanceWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinanceWorkspaceId")
                        .HasDatabaseName("IX_JournalEntries_FinanceWorkspaceId");

                    b.HasIndex("FinanceWorkspaceId", "CreatedAt")
                        .HasDatabaseName("IX_JournalEntries_FinanceWorkspaceId_CreatedAt");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.JournalEntries.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId")
                        .HasDatabaseName("IX_JournalEntryLines_FinancialAccountId");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("IX_JournalEntryLines_JournalEntryId");

                    b.HasIndex("JournalEntryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_JournalEntryLines_JournalEntryId_Sequence");

                    b.ToTable("JournalEntryLines", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Ledger.LedgerPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanceWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinanceWorkspaceId")
                        .HasDatabaseName("IX_LedgerPostings_FinanceWorkspaceId");

                    b.HasIndex("JournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerPostings_JournalEntryId");

                    b.HasIndex("FinanceWorkspaceId", "PostedAtUtc")
                        .HasDatabaseName("IX_LedgerPostings_FinanceWorkspaceId_PostedAtUtc");

                    b.ToTable("LedgerPostings", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Ledger.LedgerPostingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LedgerPostingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceJournalEntryLineId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId")
                        .HasDatabaseName("IX_LedgerPostingLines_FinancialAccountId");

                    b.HasIndex("LedgerPostingId")
                        .HasDatabaseName("IX_LedgerPostingLines_LedgerPostingId");

                    b.HasIndex("LedgerPostingId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerPostingLines_LedgerPostingId_Sequence");

                    b.HasIndex("LedgerPostingId", "SourceJournalEntryLineId")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerPostingLines_LedgerPostingId_SourceJournalEntryLineId");

                    b.ToTable("LedgerPostingLines", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformOrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformOrganizationId", "PlatformWorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("IX_FinanceWorkspaces_PlatformOrganizationId_PlatformWorkspaceId");

                    b.ToTable("FinanceWorkspaces", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Accounts.Account", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", null)
                        .WithMany()
                        .HasForeignKey("FinanceWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Invoices.Invoice", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", null)
                        .WithMany()
                        .HasForeignKey("FinanceWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Invoices.InvoiceLine", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Invoices.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.JournalEntries.JournalEntry", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", null)
                        .WithMany()
                        .HasForeignKey("FinanceWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.JournalEntries.JournalEntryLine", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VectorFlow.Finance.Domain.JournalEntries.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Ledger.LedgerPosting", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", null)
                        .WithMany()
                        .HasForeignKey("FinanceWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VectorFlow.Finance.Domain.JournalEntries.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Ledger.LedgerPostingLine", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VectorFlow.Finance.Domain.Ledger.LedgerPosting", null)
                        .WithMany("Lines")
                        .HasForeignKey("LedgerPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.JournalEntries.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Ledger.LedgerPosting", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
