// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectorFlow.Finance.Infrastructure.Persistence;

#nullable disable

namespace VectorFlow.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260719065520_AddAccounts")]
    partial class AddAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("VectorFlow.Finance.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanceWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinanceWorkspaceId")
                        .HasDatabaseName("IX_Accounts_FinanceWorkspaceId");

                    b.HasIndex("FinanceWorkspaceId", "CodeNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_FinanceWorkspaceId_CodeNormalized");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformOrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformOrganizationId", "PlatformWorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("IX_FinanceWorkspaces_PlatformOrganizationId_PlatformWorkspaceId");

                    b.ToTable("FinanceWorkspaces", (string)null);
                });

            modelBuilder.Entity("VectorFlow.Finance.Domain.Accounts.Account", b =>
                {
                    b.HasOne("VectorFlow.Finance.Domain.Workspaces.FinanceWorkspace", null)
                        .WithMany()
                        .HasForeignKey("FinanceWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
